Models/designation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace hrm.Models
{
    
    public class designation : ErrorModel
    {
        public List<designation_items> _desgnation { get; set; }
        [Required(ErrorMessage = "Please enter name.", AllowEmptyStrings = false)]
        public string desgnation_name { get; set; }
        public int deptid { get; set; }
        public List<department_items> _depts { get; set; }
    }

    public class designation_items
    {
        public string name { get; set; }
        public string _dep_name { get; set; }
        public int id { get; set; }
        public int deptid { get; set; }
    }
}

Controllers/designationsController.cs
using hrm.Database;
using hrm.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hrm.Controllers
{
    [AuthorizeVerifiedloggedin]
    public class designationsController : Controller
    {
        public List<int> _permission;
        public designationsController()
        {
            int roleid = System.Web.HttpContext.Current.Request.Cookies["_pid"] == null ? 0 : Convert.ToInt16(System.Web.HttpContext.Current.Request.Cookies["_pid"].Value.ToString());
            roleservices _ser = new roleservices();
            _permission = _ser.get_all_active_permissions_bytypeid(7, roleid);
        }
        public ActionResult Index()
        {
            if (!_permission.Contains(4))
            {
                return View("unauth");
            }
            ViewBag.permissions = _permission;
            var dept = new designationservices();
            var _model = dept.get_all_active_designations();
            string message = "";
            if (TempData["error"] != null)
            {
                message = TempData["error"].ToString();
            }
            _model._depts = GetDepartments();
            _model = new helper().GenerateError<designation>(_model, message);
            return View(_model);
        }

        public ActionResult update()
        {
            ViewBag.permissions = _permission;
            var dept = new designationservices();
            var _model = dept.get_all_active_designations();
            _model._depts = GetDepartments();
            _model = new helper().GenerateError<designation>(_model, _model.error_text);
            return View("index", _model);
        }

        [HttpPost]
        public ActionResult Index(designation _model)
        {
            var dept = new designationservices();
            int userid = Convert.ToInt16(Request.Cookies["_xid"].Value.ToString());
            ViewBag.permissions = _permission;
            int deptid = _model.deptid;
            var error_text = dept.add_new_designations(_model.desgnation_name, userid,_model.deptid);
            if (!error_text.ToLower().Contains("error"))
            {
                ModelState.Clear();
            }
            _model = dept.get_all_active_designations();
            _model._depts = GetDepartments();
            _model.deptid = deptid;
            _model = new helper().GenerateError<designation>(_model, error_text);
            return View(_model);
        }


        [HttpPost]
        public ActionResult update(string designation,int desgid, int depid)
        {
            var dept = new designationservices();
            int userid = Convert.ToInt16(Request.Cookies["_xid"].Value.ToString());
            ViewBag.permissions = _permission;
            var error_text = dept.update_designations(designation, desgid, depid, userid);
            designation _model = new designation();
            _model = dept.get_all_active_designations();
            _model._depts = GetDepartments();
            _model = new helper().GenerateError<designation>(_model, error_text);
            return View("index", _model);
        }


        public ActionResult delete(int desgid)
        {
            if (!_permission.Contains(24))
            {
                return View("unauth");
            }
            var dept = new designationservices();
            int userid = Convert.ToInt16(Request.Cookies["_xid"].Value.ToString());
            ViewBag.permissions = _permission;
            var error_text = dept.delete_designations(desgid, userid);
            designation _model = new designation();
            _model = dept.get_all_active_designations();
            _model._depts = GetDepartments();
            _model = new helper().GenerateError<designation>(_model, error_text);
            return View("index", _model);
        }


        public List<department_items> GetDepartments()
        {
            var dept = new departmentservices();
            var _model = dept.get_all_active_departments();
            return _model._dept;
        }
    }
}

Views/designations/Index.cshtml
@{
    ViewBag.Title = "Designations";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int _count = 0;
    var permission = (List<int>)ViewBag.permissions;
}

@model hrm.Models.designation

<div class="p-10">
    @*<h2 class="page-title">DESIGNATIONS</h2>*@
</div>
<div class="p-30 p-t-none p-b-none">
    @if (!string.IsNullOrEmpty(Model.error_text))
    {
        <div class="alert alert-@Model.alertclass alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
            @Model.error_text
        </div>
    }

    <div id="upload" class="modal fade" data-backdrop="static" data-keyboard="false" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <h4 class="modal-title" id="myModalLabel">Upload Designations</h4>
                </div>
                @using (Html.BeginForm("designation", "import", FormMethod.Post, new { @id = "frmsendsms", @enctype = "multipart/form-data" }))
                {

                    <div class="modal-body">
                        <div class="row">
                            <div class="col-sm-12 col-md-12 col-lg-12">

                                <div class="form-group">
                                    <label style="width:100%">Upload a CSV formatted file:</label>
                                    <div class="input-group input-group-file">
                                        <span class="input-group-btn">
                                            <span class="btn btn-primary btn-file">
                                                Browse <input required type="file" id="files" accept=".csv" class="form-control" name="file">
                                            </span>
                                        </span>
                                        <input type="text" class="form-control" readonly="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Department Name :</label>
                                    <select class="selectpicker form-control" data-live-search="true" id="depidpopup" name="department">
                                        @foreach (var item in Model._depts)
                                        {
                                            <option value="@item.id">@item.name</option>
                                        }
                                    </select>
                                </div>
                                <div class="clearfix"></div>
                                <div class="form-group">
                                    <label style="width:100%">Download Template:</label>
                                    <a href="@Url.Content("~/csvfiles/designation.csv")" download="">  <img src="@Url.Content("~/Content/Images/csv.png")" style="width:100px;" /></a>

                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" id="submit-file" class="btn btn-success">Import</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                }
            </div>

        </div>

    </div>

    <div id="mdlupdate" class="modal fade" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <h4 class="modal-title" id="myModalLabel">Edit DESIGNATIONS</h4>
                </div>
                @using (Html.BeginForm("update", "designations", FormMethod.Post, new { @id = "frmsendsms" }))
                {<div class="modal-body">
                        <div class="form-group">
                            <label>DESIGNATIONS Name :</label>
                            <input type="text" class="form-control" required="" id="designation" name="designation">
                            <input type="hidden" name="desgid" id="desgid" />
                        </div>
                        <div class="form-group">
                            <label>Department Name :</label>

                            <select class="selectpicker form-control" data-live-search="true" id="depid" name="depid">
                                <option selected value="0">Department</option>
                                @foreach (var item in Model._depts)
                                {
                                    <option value="@item.id">@item.name</option>
                                }
                            </select>
                        </div>
                    </div>
                 <div class="modal-footer">
                     <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> Update</button>
                     <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-close"></i> Close</button>

                 </div>
                }
            </div>
        </div>

    </div>


    <div class="row">
        @if (permission.Contains(26))
        {
            <div class="col-lg-4">
                <div class="panel">
                    <div class="panel-body">
                        @using (Html.BeginForm("index", "designations", FormMethod.Post, new { @id = "frmsendsms" }))
                        {
                            <div class="panel-heading">
                                <h3 class="panel-title"> Add DESIGNATIONS</h3>
                            </div>
                            <div class="form-group">
                                <label>DESIGNATIONS Name</label>
                                <span class="help">e.g. "Software Engineer"</span>
                                @Html.TextBoxFor(a => a.desgnation_name, new { @class = "form-control" })
                                @Html.ValidationMessageFor(a => a.desgnation_name)
                            </div>
                            <div class="form-group">
                                <label>Department Name</label>

                                <select class="selectpicker form-control" data-live-search="true" id="deptid" name="deptid">
                                    <option selected value="0">Department</option>
                                    @foreach (var item in Model._depts)
                                    {
                                        <option value="@item.id">@item.name</option>
                                    }
                                </select>
                            </div>
                            <button type="submit" class="btn btn-success btn-sm pull-right"><i class="fa fa-plus"></i> Add </button>
                        }
                    </div>
                </div>
            </div>
        }
        <div class="col-lg-8">
            <div class="panel">
                <div class="panel-heading" style="padding-left:20px;">
                    <h3 class="panel-title">
                        All DESIGNATIONS
                        @if (permission.Contains(25))
                        {
                            <a class="btn btn-success btn-sm pull-right" style="margin-right:8px;" onclick="Uploadfile()" href="#">
                                <i class="fa fa-cloud-upload"></i> Upload
                            </a>
                        }
                    </h3>
                </div>
                <div class="panel-body p-none">
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table data-table table-hover table-ultra-responsive dataTable no-footer" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info">
                                <thead>
                                    <tr>
                                        <th>SL#</th>
                                        <th>DESIGNATION</th>
                                        <th>DEPARTMENT</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model._desgnation)
                                    {
                                        _count = _count + 1;
                                        <tr>
                                            <td>@_count</td>
                                            <td>

                                                @if (permission.Contains(23))
                                                {
                                                    <a href="#" onclick="update('@item.id','@item.name','@item.deptid')">@item.name</a>
                                                }
                                                else
                                                { <a href="#" class="disabledbtn" data-msg="you are not authorized to edit selected designation">@item.name</a>
                                                  
                                                }
                                            </td>
                                            <td><p>@item._dep_name</p></td>
                                            <td>
                                                <div class="btn-group pos-static">
                                                    <a class="customedropdown" data-toggle="customedropdown" aria-haspopup="true" aria-expanded="false">
                                                        <i class="fa fa-ellipsis-v fn21"></i>
                                                    </a>
                                                    <div class="dropdown-menu customdropdown-menu" x-placement="bottom-start" style="top: 0px; transform: translate3d(-96px, -18px, 0px);will-change: transform;position: absolute;left: 0px;">

                                                        @if (permission.Contains(23))
                                                        {
                                                            <a class="btn btn-success btn-xs" onclick="update('@item.id','@item.name','@item.deptid')"><i class="fa fa-edit"></i> Edit</a>
                                                        }
                                                        else
                                                        {
                                                            <a href="#" class="btn btn-success btn-xs disabledbtn" data-msg="you are not authorized to edit selected designation"><i class="fa fa-edit"></i> Edit</a>
                                                        }
                                                        @if (permission.Contains(24))
                                                        {
                                                            <a href="#" class="btn btn-danger btn-xs cdelete" id="@item.id"><i class="fa fa-trash"></i> Delete</a>
                                                        }
                                                        else
                                                        {
                                                            <a href="#" class="btn btn-danger btn-xs disabledbtn" data-msg="you are not authorized to delete selected designation"><i class="fa fa-trash"></i> Delete</a>
                                                        }
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    }


                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>
@if (Model.deptid != 0)
{
    <script>
        $('select[name=deptid]').val('@Model.deptid');
        $('.selectpicker').selectpicker('refresh');
    </script>
}
<script>

    function Uploadfile() {
              $('#upload').modal('show');
        }

    $(document).ready(function () {
        $('.data-table').DataTable({"bSort" : false, "pageLength": 25});
        /*For Delete Department*/
        $(".cdelete").click(function (e) {
            e.preventDefault();
            var id = this.id;
            bootbox.confirm("Are you sure?", function (result) {
                if (result) {
                    var _url = "@Url.Action("delete","designations")";
                    window.location.href = _url + "?desgid=" + id;
                }
            });
        });
    });
     function update(desgid, deptname,deptid) {
            $('#mdlupdate').modal('show');
            $("#designation").val(deptname);
         //$("#depid").val(deptid);
         $("#desgid").val(desgid);
         $('select[name=depid]').val(deptid);
         $('.selectpicker').selectpicker('refresh');
    }


</script>