Controllers/membersController.cs
using hrm.Database;
using hrm.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hrm.Controllers
{
    [AuthorizeVerifiedloggedin]
    public class membersController : Controller
    {
        public int pageid = 2;
        public List<int> _permission;
        public membersController()
        {
            int roleid = System.Web.HttpContext.Current.Request.Cookies["_pid"] == null ? 0 : Convert.ToInt16(System.Web.HttpContext.Current.Request.Cookies["_pid"].Value.ToString());
            roleservices _ser = new roleservices();
            _permission = _ser.get_all_active_permissions_bytypeid(12, roleid);
        }
        public ActionResult Index(int? statusId, int? stateid, int[] cityId = null, int[] skills = null, int[] sourceid = null, int post = 1)
        {
            if (!_permission.Contains(8))
            {
                return View("unauth");
            }
            int userid = Convert.ToInt16(Request.Cookies["_xid"].Value.ToString());
            leadmodal _model = new leadmodal();
            leadservices _services = new leadservices();
            List<int> _ctyiid = new List<int>();
            var _filtermodel = new leadfilter();
            _filtermodel = new filterservices().getfilter<leadfilter>(_filtermodel, userid, pageid);
            ViewBag.statusId = _filtermodel.statusId ?? 0;
            ViewBag.stateid = _filtermodel.stateid ?? 0;
            ViewBag.paymentstatus = string.IsNullOrEmpty(_filtermodel.jobstatus) ? _ctyiid.ToArray() : Array.ConvertAll(_filtermodel.jobstatus.Split(','), int.Parse);
            ViewBag.city = string.IsNullOrEmpty(_filtermodel.city) ? "" : _filtermodel.city;
            ViewBag.jobstatus = string.IsNullOrEmpty(_filtermodel.skiils) ? _ctyiid.ToArray() : Array.ConvertAll(_filtermodel.skiils.Split(','), int.Parse);
            ViewBag.isfilter = _filtermodel.isActiveFilter;
            ViewBag.permissions = _permission;
            // _model = _services.get_all_active_leads();
            string message = "";
            if (TempData["error"] != null)
            {
                message = TempData["error"].ToString();
            }
            _model = new helper().GenerateError<leadmodal>(_model, message);
            defaultservices _default = new defaultservices();
            ViewBag.select = _default.get_all_satets();
            _model._skills = get_all_skills();
            return View(_model);
        }


        public void update_status(int leadid, int statusid)
        {
            int userid = Convert.ToInt16(Request.Cookies["_xid"].Value.ToString());
            string memberid = "";
            if (statusid == 4)
            {
                memberid = new memberservices().getLatestMemberId();
            }
            new leadservices().update_lead_status(statusid, leadid, memberid, userid);
        }

        public JsonResult Fetchleads(int? statusId, int? stateid, int start = 0, int length = 25, int draw = 1, int searchtype = 0)
        {
            string search = Request.Params["search[value]"] == null ? "" : Request.Params["search[value]"];
            string _sourceid = Request.Params["sourceid"] == null ? "" : Request.Params["sourceid"];
            string _skills = Request.Params["skills"] == null ? "" : Request.Params["skills"];
            string _city_id = Request.Params["cityId"] == null ? "" : Request.Params["cityId"];
            int userid = Convert.ToInt16(Request.Cookies["_xid"].Value.ToString());
            var _filtermodel = new leadfilter();
            if (searchtype == 0)
            {
                _filtermodel = new filterservices().getfilter<leadfilter>(_filtermodel, userid, pageid);
                statusId = _filtermodel.statusId;
                stateid = _filtermodel.stateid;
                _sourceid = string.IsNullOrEmpty(_filtermodel.jobstatus) ? "0" : _filtermodel.jobstatus;
                _city_id = string.IsNullOrEmpty(_filtermodel.city) ? "0" : _filtermodel.city;
                _skills = string.IsNullOrEmpty(_filtermodel.skiils) ? "0" : _filtermodel.skiils;
            }
            else if (searchtype == 1)
            {
                _filtermodel.statusId = statusId;
                _filtermodel.stateid = stateid;
                _filtermodel.jobstatus = _sourceid;
                _filtermodel.city = _city_id;
                _filtermodel.skiils = _skills;
                new filterservices().save_filter<leadfilter>(_filtermodel, userid, pageid);
            }
            if (searchtype == 2)
            {
                statusId = null;
                stateid = null;
                _sourceid = "0";
                _city_id = "0";
                _skills = "0";
                new filterservices().delete_filter(userid, pageid);
                //clearsearch
            }
            int[] cityId = Array.ConvertAll(_city_id.Split(','), int.Parse);
            int[] skills = Array.ConvertAll(_skills.Split(','), int.Parse);
            int[] sourceid = Array.ConvertAll(_sourceid.Split(','), int.Parse);
            start = (start == 0 ? 1 : start + 1);
            length = (start == 1 ? length : (start - 1) + length);
            leadservices _services = new leadservices();
            datatableAjax<leadmodals> tableDate = new datatableAjax<leadmodals>();
            int total = 0;
            var _model = _services.get_all_active_leads_by_index(ref total, start, length, search, statusId, stateid, cityId, skills, sourceid);
            tableDate.draw = draw;
            tableDate.data = _model;
            tableDate.recordsFiltered = (_model.Count() > 0 ? total : 0);
            tableDate.recordsTotal = total;
            return base.Json(tableDate, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Index(int? statusId, int? stateid, int[] cityId = null, int[] skills = null, int[] sourceid = null)
        {
            leadmodal _model = new leadmodal();
            leadservices _services = new leadservices();
            List<int> _ctyiid = new List<int>();
            ViewBag.statusId = statusId ?? 0;
            ViewBag.stateid = stateid ?? 0;
            ViewBag.jobstatus = skills == null ? _ctyiid.ToArray() : skills;
            ViewBag.city = cityId == null ? "" : string.Join<int>(",", cityId);
            ViewBag.paymentstatus = sourceid == null ? _ctyiid.ToArray() : sourceid;
            ViewBag.permissions = _permission;
            _model = _services.get_all_active_leads(",", statusId, stateid, cityId, skills, sourceid);
            string message = "";
            if (TempData["error"] != null)
            {
                message = TempData["error"].ToString();
            }
            _model = new helper().GenerateError<leadmodal>(_model, message);
            defaultservices _default = new defaultservices();
            ViewBag.select = _default.get_all_satets();
            _model._skills = get_all_skills();
            return View(_model);
        }


        public ActionResult add()
        {
            if (!_permission.Contains(42))
            {
                return View("unauth");
            }
            ViewBag.permissions = _permission;
            leadmodal_item _model = new leadmodal_item();
            defaultservices _default = new defaultservices();
            ViewBag.select = _default.get_all_satets();
            _model._skills = get_all_skills();
            return View(_model);
        }

        public ActionResult edit(string token)
        {
            if (!_permission.Contains(43))
            {
                return View("unauth");
            }
            Crypto _crypt = new Crypto();
            int id = Convert.ToInt32(_crypt.DecryptStringAES(token));
            ViewBag.permissions = _permission;
            leadmodal_item _model = new leadmodal_item();
            leadservices _services = new leadservices();
            _model = _services.get_all_active_leads_byid(id);
            defaultservices _default = new defaultservices();
            ViewBag.select = _default.get_all_satets();
            var message = "";
            if (TempData["error"] != null)
            {
                message = TempData["error"].ToString();
            }
            _model = new helper().GenerateError<leadmodal_item>(_model, message);
            _model._skills = get_all_skills();
            return View(_model);
        }

        [HttpPost]
        public ActionResult add(leadmodal_item _item)
        {
            int userid = Convert.ToInt16(Request.Cookies["_xid"].Value.ToString());
            leadmodal _model = new leadmodal();
            leadservices _services = new leadservices();
            defaultservices _default = new defaultservices();
            //----------------------filter code------------------------
            List<int> _ctyiid = new List<int>();
            var _filtermodel = new leadfilter();
            _filtermodel = new filterservices().getfilter<leadfilter>(_filtermodel, userid, pageid);
            ViewBag.statusId = _filtermodel.statusId ?? 0;
            ViewBag.stateid = _filtermodel.stateid ?? 0;
            ViewBag.paymentstatus = string.IsNullOrEmpty(_filtermodel.jobstatus) ? _ctyiid.ToArray() : Array.ConvertAll(_filtermodel.jobstatus.Split(','), int.Parse);
            ViewBag.city = string.IsNullOrEmpty(_filtermodel.city) ? "" : _filtermodel.city;
            ViewBag.jobstatus = string.IsNullOrEmpty(_filtermodel.skiils) ? _ctyiid.ToArray() : Array.ConvertAll(_filtermodel.skiils.Split(','), int.Parse);
            ViewBag.isfilter = _filtermodel.isActiveFilter;
            ViewBag.permissions = _permission;
            //----------------------filter code------------------------
            _item.city_id = getcityidbystate(_item.state_id, _item.city);
            var message = _services.add_new_lead(_item, userid);
            _model = new helper().GenerateError<leadmodal>(_model, message);

Views/members/add.cshtml
@{
    ViewBag.Title = "Members";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var state = (Dictionary<int, string>)ViewBag.select;
}
@model hrm.Models.leadmodal_item
<style>
    #amount:hover {
        background-color: #F1F9FF;
    }

    .table.table-hover tbody tr:hover > td > #amount {
        background-color: #F1F9FF;
    }

    .dropdown-toggle, .multiselect-clear-filter {
        height: 42px !important;
    }

    .dropdown-menu {
        min-width: 212px;
    }

    .btn .caret {
        margin-left: 0;
        float: right;
        vertical-align: middle;
     margin-top:9px;
    }

    .btn-group, .dropdown-toggle {
        width: 100%;
        text-align: left;
    }

    .btn-default.active, .btn-default:active, .btn-default.active:focus, .btn-default:active:focus, .btn-default.active:hover, .btn-default:active:hover, .open > .dropdown-toggle.btn-default:focus, .open > .dropdown-toggle.btn-default:hover, .open > .dropdown-toggle.btn-default.focus {
        background-color: white !Important;
        border-color: grey !important;
        color: #626262 !important;
        height: 42px;
    }
</style>
<div class="p-10">
    @*<h2 class="page-title">
            Add Lead

        </h2>*@

</div>
<div class="p-30 p-t-none p-b-none">
    @if (!string.IsNullOrEmpty(Model.error_text))
    {
        <div class="alert alert-@Model.alertclass alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
            @Model.error_text
        </div>
    }


    <div class="row">
        <div class="col-lg-8">
            <div class="panel">
                <div class="panel-heading formpanel-heading">
                    <div class="col-md-6 col-sm-6">
                        <h3 class="panel-title">
                            Add Member

                        </h3>
                    </div>
                    <div class="col-md-6 col-sm-6 topbuttondiv">
                        <a class="btn btn-success btn-sm pull-right" href="@Url.Action("index","members")">
                            <i class="fa fa-arrow-left"></i> Members List
                        </a>
                    </div>

                </div>
                <div class="panel-body">
                    @using (Html.BeginForm("add", "members", FormMethod.Post, new { @id = "frmmembers" }))
                    {

                        <div class="form-group col-md-6 col-sm-12">
                            <label>First Name</label>
                            @Html.TextBoxFor(a => a.firstname, new { @class = "form-control capitalize" })
                            @Html.ValidationMessageFor(a => a.firstname)
                        </div>
                        <div class="form-group col-md-6 col-sm-12">
                            <label>Last Name</label>
                            @Html.TextBoxFor(a => a.lastname, new { @class = "form-control capitalize" })
                            @Html.ValidationMessageFor(a => a.lastname)
                        </div>
                        <div class="form-group col-md-6 col-sm-12">
                            <label>Email Address</label>
                            @Html.TextBoxFor(a => a.email, new { @class = "form-control", @type = "email" })
                            @Html.ValidationMessageFor(a => a.email)
                        </div>
                        <div class="form-group col-md-6 col-sm-12">
                            <label>Phone</label>
                            @Html.TextBoxFor(a => a.phone, new { @class = "form-control phonenumber", @maxlength = "12" })
                            @Html.ValidationMessageFor(a => a.phone)
                        </div>
                        <div class="form-group col-md-6 col-sm-12">
                            <label>Company  </label>
                            @Html.TextBoxFor(a => a.Company, new { @class = "form-control" })

                        </div>
                        <div class="form-group col-md-6 col-sm-12">
                            <label>Rate</label>
                            <span class="help">e.g. "10"</span>
                            @Html.TextBoxFor(a => a.rate, new { @class = "form-control ratetext" })
                            @Html.ValidationMessageFor(a => a.rate)
                        </div>
                        <div class="form-group col-md-6 col-sm-12">
                            <label>Website</label>
                            @Html.TextBoxFor(a => a.Website, new { @class = "form-control" })

                        </div>
                        <div class="form-group col-md-6 col-sm-12">
                            <label>Linkedin</label>
                            @Html.TextBoxFor(a => a.LinkedIn, new { @class = "form-control" })

                        </div>


                        <div class="form-group col-md-6 col-sm-12">
                            <label>City</label>
                            @Html.TextBoxFor(a => a.city, new { @class = "form-control" })
                        </div>
                        <div class="form-group col-md-6 col-sm-12">
                            <label>State</label>

                            <select id="state_id" data-live-search="true" name="state_id" class="selectpicker form-control">
                                <option value="0">State</option>
                                @foreach (var item in state)
                                {
                                    <option value="@item.Key">@item.Value</option>
                                }
                            </select>
                        </div>
                        <div class="form-group col-md-6 col-sm-12">
                            <label>Skills</label>
                            <select id="skills" multiple name="skill" class="form-control">
                                @foreach (var item in Model._skills)
                                {
                                    <option value="@item.id">@item.name</option>
                                }
                            </select>
                        </div>
                        <div class="form-group col-md-6 col-sm-12">
                            <label>Category</label>
                            <select name="srcid" id="srcid" class="selectpicker form-control">
                                <option value="2">Technician</option>
                                <option value="3">Customer</option>
                                <option value="1">Employee applicant</option>
                            </select>
                        </div>
                        <div class="form-group   col-md-6 col-sm-12">
                            <label>Status</label>
                            <select name="statusid" id="statusid" class="selectpicker form-control">
                                <option value="1">New</option>
                                <option value="2">Contacted</option>
                                <option value="6">Follow up</option>
                                <option value="3">Interviewed</option>
                                <option value="4">Converted</option>
                                <option value="5">Declined</option>
                            </select>
                        </div>
                        <button type="submit" class="btn btn-success btn-sm pull-right"><i class="fa fa-plus"></i> Add </button>
                    }
                </div>
            </div>
        </div>


    </div>

</div>
<script>
    $(document).ready(function () {
        $("#skills").multiselect({enableCaseInsensitiveFiltering:true,
            enableFiltering: true, buttonText: function (options, select) {
                return 'Skills';
            },
        });
    });
       
</script>

Views/members/edit.cshtml
@{
    ViewBag.Title = "Members";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var state = (Dictionary<int, string>)ViewBag.select;
    int tab =ViewBag.tab==null?1: (int)ViewBag.tab;
    }

<style>
    #amount:hover {
        background-color: #F1F9FF;
    }

    .table.table-hover tbody tr:hover > td > #amount {
        background-color: #F1F9FF;
    }

    .dropdown-toggle, .multiselect-clear-filter {
        height: 42px !important;
    }

    .dropdown-toggle, .btn-group {
        width: 100% !important;
        text-align: left !important;
    }

    .dropdown-menu {
        min-width: 212px;
    }

    .btn-default.active, .btn-default:active, .btn-default.active:focus, .btn-default:active:focus, .btn-default.active:hover, .btn-default:active:hover, .open > .dropdown-toggle.btn-default:focus, .open > .dropdown-toggle.btn-default:hover, .open > .dropdown-toggle.btn-default.focus {
        background-color: white !Important;
        border-color: grey !important;
        color: #626262 !important;
        height: 42px;
    }
</style>
@model hrm.Models.leadmodal_item

<div class="p-10">
    @*<h2 class="page-title">
            Edit Lead

        </h2>*@

</div>
<div class="p-30 p-t-none p-b-none">
    @if (!string.IsNullOrEmpty(Model.error_text))
    {
        <div class="alert alert-@Model.alertclass alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
            @Model.error_text
        </div>
    }


<div class="row">
    <div class="col-lg-4">
        <div class="panel">
            <div class="panel-heading formpanel-heading">
                <div class="col-md-12 col-sm-12">
                    <h3 class="panel-title">
                        (@(Model.firstname + ' ' + Model.lastname)) Basic Info
                    </h3>
                </div>

            </div>
            <div class="panel-body">
                @using (Html.BeginForm("update", "Members", FormMethod.Post, new { @id = "frmsendsms" }))
                {
                    <div class="form-group">
                        <label>First Name</label>
                        @Html.TextBoxFor(a => a.firstname, new { @class = "form-control capitalize" })
                        @Html.ValidationMessageFor(a => a.firstname)
                        @Html.HiddenFor(a => a.leadId)
                    </div>
                    <div class="form-group">
                        <label>Last Name</label>
                        @Html.TextBoxFor(a => a.lastname, new { @class = "form-control capitalize" })
                        @Html.ValidationMessageFor(a => a.lastname)
                    </div>
                    <div class="form-group">
                        <label>Email Address</label>
                        @Html.TextBoxFor(a => a.email, new { @class = "form-control", @type = "email" })
                        @Html.ValidationMessageFor(a => a.email)
                    </div>
                    <div class="form-group">
                        <label>Phone</label>
                        @Html.TextBoxFor(a => a.phone, new { @class = "form-control phonenumber" })
                        @Html.ValidationMessageFor(a => a.phone)
                    </div>
                    <div class="form-group">
                        <label>Company  </label>
                        @Html.TextBoxFor(a => a.Company, new { @class = "form-control" })
                      
                    </div>
                    <div class="form-group">
                        <label>Website</label>
                        @Html.TextBoxFor(a => a.Website, new { @class = "form-control" })
                      
                    </div>
                    <div class="form-group">
                        <label>Linkedin</label>
                        @Html.TextBoxFor(a => a.LinkedIn, new { @class = "form-control" })
                      
                    </div>
                    <div class="form-group">
                        <label>Rate</label>
                        <span class="help">e.g. "10"</span>
                        @Html.TextBoxFor(a => a.rate, new { @class = "form-control ratetext" })
                        @Html.ValidationMessageFor(a => a.rate)
                    </div>
                    <div class="form-group">
                        <label>Skills</label>
                        <select class="form-control" multiple name="skill" id="skill">
                            @foreach (var item in Model._skills)
                            {
                                if (Model.skill != null && Model.skill.Contains(item.id))
                                {
                                    <option selected value="@item.id">@item.name</option>
                                }
                                else
                                {
                                    <option value="@item.id">@item.name</option>
                                }

                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label>State</label>
                        <select id="state_id" data-live-search="true" name="state_id" class="selectpicker form-control">
                            <option value="0">State</option>
                            @foreach (var item in state)
                            {
                                if (item.Key == Model.state_id)
                                {
                                    <option selected value="@item.Key">@item.Value</option>

                                }
                                else
                                {
                                    <option value="@item.Key">@item.Value</option>

                                }
                            }
                        </select>

                    </div>
                    <div class="form-group">
                        <label>City</label>
                        @Html.TextBoxFor(a => a.city, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Category</label>
                        <select name="srcid" id="srcid" class="selectpicker form-control">
                            <option @(Model.srcid == 2 ? "selected" : "") value="2">Technician</option>
                            <option @(Model.srcid == 3 ? "selected" : "") value="3">Customer</option>
                            <option @(Model.srcid == 1 ? "selected" : "") value="1">Employee applicant</option>

                        </select>
                    </div>
                    <div class="form-group">
                        <label>Status</label>
                        <select name="statusid" id="statusid" class="selectpicker form-control">
                            <option @(Model.statusid == 1 ? "selected" : "") value="1">New</option>
                            <option @(Model.statusid == 2 ? "selected" : "") value="2">Contacted</option>
                            <option @(Model.statusid == 6 ? "selected" : "") value="6">Follow up</option>
                            <option @(Model.statusid == 3 ? "selected" : "") value="3">Interviewed</option>
                            <option @(Model.statusid == 4 ? "selected" : "") value="4">Converted</option>
                            <option @(Model.statusid == 5 ? "selected" : "") value="5">Declined</option>
                        </select>
                    </div>



                    <button type="submit" class="btn btn-success btn-sm pull-right"><i class="fa fa-save"></i> Update </button>
                }
            </div>
        </div>
    </div>

    <div class="col-lg-8">

        <div class="panel">
            <div class="panel-heading formpanel-heading">
                <div class="col-md-6 col-sm-6">
                    <h3 class="panel-title">
                        Discussion
                    </h3>
                </div>
                <div class="col-md-6 col-sm-6 topbuttondiv">
                    <a class="btn btn-success btn-sm pull-right" href="@Url.Action("index","Members")">
                        <i class="fa fa-arrow-left"></i> Members List
                    </a>
                </div>
            </div>


            <div class="p-30 p-t-none p-b-none">
                <div class="row">
                    <div class="col-lg-12">
                        <!-- Nav tabs -->
                       
                        <!-- Tab panes -->
                        <div class="tab-content p-20">
                            <div role="tabpanel" class="tab-pane active" id="task_discussion">
                                @using (Html.BeginForm("update", "Members", FormMethod.Post, new { @id = "frmsendsms" }))
                                {
                                    <div class="row">
                                        <div class="form-group">
                                            <label>Leave Comment</label>
                                            @Html.TextAreaFor(a => a.comment, new { @class = "textarea-wysihtml5 form-control", @rows = "7" })
                                            <input type="hidden" name="type" value="2" />
                                            @Html.HiddenFor(a => a.leadId)
                                        </div>
                                        <div class="col-md-12">
                                            <button type="submit" class="btn btn-success pull-right"><i class="fa fa-reply"></i> Reply</button>


                                        </div>
                                    </div>

                                }
                                <br>
                                <hr>

                                <table class="table data-table table-condensed table-hover table-ultra-responsive dataTable no-footer">
                                    <thead>
                                        <tr>
                                            <th style="width: 25%;">Member</th>
                                            <th style="width: 55%;">Comment</th>
                                            <th style="width: 20%;">Last Update</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model._Comments)
                                        {
                                            <tr>
                                                <td nowrap style="width: 25%;">@item.createdby</td>
                                                <td style="width: 55%;">@Html.Raw(item.Comment)</td>
                                                <td nowrap style="width: 20%;">@item.CreatedDate</td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>

                            </div>

                            
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>

</div>
<script>

    $("#skill").multiselect({enableCaseInsensitiveFiltering:true,enableFiltering: true,buttonText: function(options, select) {
                return 'Skills';
            },});
    $(document).ready(function () {
         $('.data-table').DataTable({ 'bSort': false, "pageLength": 25 });
          
    });
</script>