Controllers/payController.cs
using hrm.Database;
using hrm.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hrm.Controllers
{
    [AuthorizeVerifiedloggedin]
    public class payController : Controller
    {
        public int pageid = 1;
        public List<int> _permission;
        public payController()
        {
            int roleid = System.Web.HttpContext.Current.Request.Cookies["_pid"] == null ? 0 : Convert.ToInt16(System.Web.HttpContext.Current.Request.Cookies["_pid"].Value.ToString());
            roleservices _ser = new roleservices();
            _permission = _ser.get_all_active_permissions_bytypeid(11, roleid);
        }
        public class paymodal
        {
            public string amount { get; set; }
            public string purchase_date { get; set; }
        }
        public JsonResult getpay()
        {
            List<paymodal> _mdl = new List<paymodal>();
            attandanceservices _ser = new attandanceservices();
            var model = _ser.get_all_active_attandance_dashboard(null, null, null, null, isyear: true);
            int userid = Convert.ToInt16(Request.Cookies["_xid"].Value.ToString());
            //if (!_permission.Contains(1055))
            //{
            //    model = _ser.get_all_active_attandance_byuserid(userid, null, null);
            //}
            foreach (var item in model._attandance)
            {
                paymodal _item = new paymodal();
                _item.amount = item.Pay.Replace("$", "");
                _item.purchase_date = item.date;
                _mdl.Add(_item);
            }
            return Json(_mdl, JsonRequestBehavior.AllowGet);
        }
        public JsonResult FetchAdminPayment(int? memberId, int? stateid, int? paymentstatus, int start = 0, int length = 25, int draw = 1, int searchtype = 0)
        {
            List<int> _ctyiid = new List<int>();
            string search = Request.Params["search[value]"] == null ? "" : Request.Params["search[value]"];
            int userid = Convert.ToInt16(Request.Cookies["_xid"].Value.ToString());
            string _cityId = "";
            string _jobstatus = "";
            var _filtermodel = new payfilter();
            _cityId = Request.Params["cityId"] == null ? "" : Request.Params["cityId"];
            _jobstatus = Request.Params["jobstatus"] == null ? "" : Request.Params["jobstatus"];
            if (searchtype == 0)
            {
                _filtermodel = new filterservices().getfilter<payfilter>(_filtermodel, userid, pageid);
                memberId = _filtermodel.memberId;
                stateid = _filtermodel.stateid;
                _jobstatus = string.IsNullOrEmpty(_filtermodel.jobstatus) ? "0" : _filtermodel.jobstatus;
                _cityId = string.IsNullOrEmpty(_filtermodel.cityId) ? "0" : _filtermodel.cityId;
                paymentstatus = _filtermodel.paymentstatus;
            }
            else if (searchtype == 1)
            {
                _filtermodel.memberId = memberId;
                _filtermodel.stateid = stateid;
                _filtermodel.jobstatus = _jobstatus;
                _filtermodel.cityId = _cityId;
                _filtermodel.paymentstatus = paymentstatus;
                new filterservices().save_filter<payfilter>(_filtermodel, userid, pageid);
            }
            if (searchtype == 2)
            {
                memberId = null;
                stateid = null;
                _jobstatus = "0";
                _cityId = "0";
                paymentstatus = null;
                new filterservices().delete_filter(userid, pageid);
                //clearsearch
            }
            int[] jobstatus = Array.ConvertAll(_jobstatus.Split(','), int.Parse);
            int[] cityId = Array.ConvertAll(_cityId.Split(','), int.Parse);
            start = (start == 0 ? 1 : start + 1);
            length = (start == 1 ? length : (start - 1) + length);
            attandanceservices _ser = new attandanceservices();
            datatableAjax<attandanceadmins> tableDate = new datatableAjax<attandanceadmins>();
            int total = 0;
            var _model = _ser.get_all_active_attandance_byIndex(length, start, ref total, memberId, stateid, jobstatus, paymentstatus, cityId, search);
            tableDate.draw = draw;
            tableDate.data = _model;
            tableDate.recordsFiltered = (_model.Count() > 0 ? total : 0);
            tableDate.recordsTotal = total;
            return base.Json(tableDate, JsonRequestBehavior.AllowGet);
        }
        public JsonResult FetchmemberPayment(int? memberId, int? stateid, int? paymentstatus, int start = 0, int length = 25, int draw = 1, int searchtype = 0)
        {
            List<int> _ctyiid = new List<int>();
            string search = Request.Params["search[value]"] == null ? "" : Request.Params["search[value]"];
            int userid = Convert.ToInt16(Request.Cookies["_xid"].Value.ToString());
            string _cityId = "";
            string _jobstatus = "";
            var _filtermodel = new payfilter();
            _cityId = Request.Params["cityId"] == null ? "" : Request.Params["cityId"];
            _jobstatus = Request.Params["jobstatus"] == null ? "" : Request.Params["jobstatus"];
            if (searchtype == 0)
            {
                _filtermodel = new filterservices().getfilter<payfilter>(_filtermodel, userid, pageid);
                memberId = _filtermodel.memberId;
                stateid = _filtermodel.stateid;
                _jobstatus = string.IsNullOrEmpty(_filtermodel.jobstatus) ? "0" : _filtermodel.jobstatus;
                _cityId = string.IsNullOrEmpty(_filtermodel.cityId) ? "0" : _filtermodel.cityId;
                paymentstatus = _filtermodel.paymentstatus;
            }
            else if (searchtype == 1)
            {
                _filtermodel.memberId = memberId;
                _filtermodel.stateid = stateid;
                _filtermodel.jobstatus = _jobstatus;
                _filtermodel.cityId = _cityId;
                _filtermodel.paymentstatus = paymentstatus;
                new filterservices().save_filter<payfilter>(_filtermodel, userid, pageid);
            }
            if (searchtype == 2)
            {
                memberId = null;
                stateid = null;
                _jobstatus = "0";
                _cityId = "0";
                paymentstatus = null;
                new filterservices().delete_filter(userid, pageid);
                //clearsearch
            }
            int[] jobstatus = Array.ConvertAll(_jobstatus.Split(','), int.Parse);
            int[] cityId = Array.ConvertAll(_cityId.Split(','), int.Parse);
            start = (start == 0 ? 1 : start + 1);
            length = (start == 1 ? length : (start - 1) + length);
            attandanceservices _ser = new attandanceservices();
            datatableAjax<attandanceadmins> tableDate = new datatableAjax<attandanceadmins>();
            int total = 0;
            var _model = _ser.get_all_active_attandance_byIndex(length, start, ref total, memberId, stateid, jobstatus, paymentstatus, cityId, search, userid);
            tableDate.draw = draw;
            tableDate.data = _model;
            tableDate.recordsFiltered = (_model.Count() > 0 ? total : 0);
            tableDate.recordsTotal = total;
            return base.Json(tableDate, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Index(int? memberId, int? stateid, int? paymentstatus, int[] cityId = null, int[] jobstatus = null, string token = "")
        {
            if (!_permission.Contains(9))
            {
                return View("unauth");
            }
            Crypto _crypt = new Crypto();
            int userid = Convert.ToInt16(Request.Cookies["_xid"].Value.ToString());
            List<int> _ctyiid = new List<int>();
            ViewBag.permissions = _permission;
            var _filtermodel = new payfilter();
            _filtermodel = new filterservices().getfilter<payfilter>(_filtermodel, userid, pageid);
            ViewBag.memberId = _filtermodel.memberId ?? 0;
            ViewBag.stateid = _filtermodel.stateid ?? 0;
            ViewBag.jobstatus = string.IsNullOrEmpty(_filtermodel.jobstatus) ? _ctyiid.ToArray() : Array.ConvertAll(_filtermodel.jobstatus.Split(','), int.Parse);
            ViewBag.city = string.IsNullOrEmpty(_filtermodel.cityId) ? "" : _filtermodel.cityId;
            ViewBag.paymentstatus = _filtermodel.paymentstatus ?? 0;
            ViewBag.isfilter = _filtermodel.isActiveFilter;
            attandanceservices _ser = new attandanceservices();
            var mes = "";
            string view = "adminpay";
            if (!string.IsNullOrEmpty(token))
            {
                int id = Convert.ToInt32(_crypt.DecryptStringAES(token));
                mes = _ser.remove_pay(id);
            }
            var model = new attandanceadmin();// _ser.get_all_active_attandance(memberId, stateid, jobstatus, paymentstatus);

            ViewBag.isadmin = true;
            if (!_permission.Contains(1055))
            {
                view = "memberpay";
                // model = _ser.get_all_active_attandance_byuserid(userid, jobstatus, paymentstatus);
                ViewBag.isadmin = false;
            }
            model = new helper().GenerateError<attandanceadmin>(model, mes);
            defaultservices _default = new defaultservices();
            ViewBag.select = _default.get_all_satets();
            return View(view, model);
        }

        [HttpPost]
        public ActionResult Index(int? memberId, int? stateid, int? paymentstatus, int[] cityId = null, int[] jobstatus = null, int print = 0)
        {
            List<int> _ctyiid = new List<int>();
            ViewBag.permissions = _permission;
            ViewBag.memberId = memberId ?? 0;
            ViewBag.stateid = stateid ?? 0;

Views/pay/add.cshtml
@{
    ViewBag.Title = "Pay";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

@model hrm.Models.attandanceadmin_items

<div class="p-10">
    @*<h2 class="page-title">
            Add Attandance

        </h2>*@

</div>
<div class="p-30 p-t-none p-b-none">
    @if (!string.IsNullOrEmpty(Model.error_text))
    {
        <div class="alert alert-@Model.alertclass alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
            @Model.error_text
        </div>
    }
    <div class="row">
        <div class="col-lg-8">
            <div class="panel">
                <div class="panel-heading formpanel-heading">
                    <div class="col-md-6 col-sm-6">
                        <h3 class="panel-title">
                            Add Pay

                        </h3>
                    </div>
                    <div class="col-md-6 col-sm-6 topbuttondiv">
                        <a class="btn btn-success btn-sm pull-right" href="@Url.Action("index","pay")">
                            <i class="fa fa-arrow-left"></i> Pay List
                        </a>
                    </div>

                </div>
                <div class="panel-body">
                    @using (Html.BeginForm("add", "pay", FormMethod.Post, new { @id = "frmsendsms", @enctype = "multipart/form-data" }))
                    {
                        <div class="form-group">
                            <label>Technician</label>
                            <select class="selectpicker form-control " data-live-search="true" name="memberid" onchange="getrate()" id="memberid">
                                <option value="0">TECHNICIAN</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Job</label>
                            <select class="selectpicker form-control " data-live-search="true" name="jobid" id="jobid">
                                <option value="0">Job</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Date</label>
                            @Html.TextBoxFor(a => a.startdate, new { @class = "form-control datePicker" })
                            @Html.ValidationMessageFor(a => a.startdate)
                        </div>
                        <div class="form-group">
                            <label>Start time</label>
                            @Html.TextBoxFor(a => a.starttime, new { @class = "form-control timePicker" })
                            @Html.ValidationMessageFor(a => a.starttime)
                        </div>
                        <div class="form-group">
                            <label>End time</label>
                            @Html.TextBoxFor(a => a.endtime, new { @class = "form-control timePicker" })
                            @Html.ValidationMessageFor(a => a.endtime)
                        </div>
                        <div class="form-group">
                            <label>Hourly rate</label>
                            @Html.TextBoxFor(a => a._memberrate, new { @class = "form-control ratetext", @id = "_memberrate" })
                            @Html.ValidationMessageFor(a => a._memberrate)
                        </div>
                        <div class="form-group">
                            <label>Expense</label>
                            @Html.TextBoxFor(a => a.expnse, new { @class = "form-control ratetext", @id = "_expense" })
                        </div>
                        <div class="form-group">
                            <label>upload Document</label>
                        </div>
                        <div class="form-group input-group input-group-file">
                            <span class="input-group-btn">
                                <span class="btn btn-primary btn-file">
                                    Browse <input type="file" class="form-control" name="file">
                                </span>
                            </span>
                            <input type="text" class="form-control" readonly="">
                        </div>
                        <div class="form-group">
                            <label>Comment</label>
                            @Html.TextAreaFor(a => a.comment, new { @class = "textarea-wysihtml5 form-control", @rows = "6" })
                        </div>
                        <button type="submit" class="btn btn-success btn-sm pull-right"><i class="fa fa-plus"></i> Add </button>
                    }
                </div>
            </div>
        </div>


    </div>

</div>
<script>
    $("form").on("submit", function (e) {
        var memberid = $("#memberid").val();
        if (memberid == 0) {
              alertify.log('Please select Technician', 'error', 5000);
              $("#memberid").focus();
            e.preventDefault();
        }
        var jobid = $("#jobid").val();
        if (jobid == 0) {
              alertify.log('Please select Job', 'error', 5000);
              $("#jobid").focus();
            e.preventDefault();
        }
    });

    function getrate() {
        var memberid = $("#memberid").val();
        if (memberid != 0) {
            var _url = "@Url.Action("get_member_rate","users")"+"?id="+memberid;
            $.get(_url, function (data) {
                $("#_memberrate").val(data);
            });
        } else {
            $("#_memberrate").val("$1");
        }
    }

   

    function getjobdetail(jobid) {
            var _url = "@Url.Action("getjob","jobs")"+"?id="+jobid;
            $.get(_url, function (data) {
                $("#startdate").val(data.sdate);
                $("#starttime").val(data.stime);
                $("#endtime").val(data.etime);
                $("#_expense").val(data.Expense);
            });
    }
     get_Manager_selectbyid('memberid', 'Technician','T');
    //get_jobs('jobid','Job');
         function get_Manager_selectbyid(cntrl,_val,type) {
            var dataString = 'optvalue='+_val+"&type="+type;
                    $.ajax
                        ({
                            type: "POST",
                            url: '@Url.Action("get_all_member","default")',
                            data: dataString,
                            cache: false,
                            success: function (data) {
                                $("#"+cntrl).html(data).removeAttr('disabled').selectpicker('refresh');
                            }
                        });

    }
    $("#memberid").on("change", function () {
        var _mbrid = $("#memberid").val();
        get_jobs('jobid', 'Job',_mbrid);
    });

    $("#jobid").on("change", function () {
        var _jobid = $("#jobid").val();
        getjobdetail(_jobid);
    });

    function get_jobs(cntrl,_val,memberid) {
            var dataString = 'optvalue='+_val+'&memberid='+memberid+"&forpay=True";
                    $.ajax
                        ({
                            type: "POST",
                            url: '@Url.Action("get_assigned_jobs","default")',
                            data: dataString,
                            cache: false,
                            success: function (data) {
                                $("#"+cntrl).html(data).removeAttr('disabled').selectpicker('refresh');
                            }
                        });

        }
</script>

Views/pay/add_user.cshtml
@{
    ViewBag.Title = "Attandance";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int userid = (int)ViewBag.userid;
    int jobid=(int)ViewBag.jobid;
}

@model hrm.Models.attandanceadmin_items

<div class="p-10">
</div>
<div class="p-30 p-t-none p-b-none">
    @if (!string.IsNullOrEmpty(Model.error_text))
    {
        <div class="alert alert-@Model.alertclass alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
            @Model.error_text
        </div>
    }
    <div class="row">
        <div class="col-lg-8">
            <div class="panel">
                <div class="panel-heading formpanel-heading">
                    <div class="col-md-6 col-sm-6">
                        <h3 class="panel-title">
                            Add Pay

                        </h3>
                    </div>
                    <div class="col-md-6 col-sm-6 topbuttondiv">
                        <a class="btn btn-success btn-sm pull-right" href="@Url.Action("index","pay")">
                            <i class="fa fa-arrow-left"></i> Pay List
                        </a>
                    </div>

                </div>
                <div class="panel-body">
                    @using (Html.BeginForm("add", "pay", FormMethod.Post, new { @id = "frmsendsms", @enctype = "multipart/form-data" }))
                    {

                        <div class="form-group">
                            <label>Technician</label>
                            <select class="selectpicker form-control " data-live-search="true" name="memberid" id="memberid">
                                <option value="0">Technician</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Job</label>
                            <select class="selectpicker form-control " data-live-search="true" name="jobid" id="jobid">
                                <option value="0">Job</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Date</label>
                            @Html.TextBoxFor(a => a.startdate, new { @class = "form-control datePicker" })
                            @Html.ValidationMessageFor(a => a.startdate)
                        </div>
                        <div class="form-group">
                            <label>Start time</label>
                            @Html.TextBoxFor(a => a.starttime, new { @class = "form-control timePicker" })
                            @Html.ValidationMessageFor(a => a.starttime)
                        </div>
                        <div class="form-group">
                            <label>End time</label>
                            @Html.TextBoxFor(a => a.endtime, new { @class = "form-control timePicker" })
                            @Html.ValidationMessageFor(a => a.endtime)
                        </div>
                        <div class="form-group">
                            <label>Hourly rate</label>
                            @Html.TextBoxFor(a => a._memberrate, new { @class = "form-control ratetext", @id = "_memberrate" })
                            @Html.ValidationMessageFor(a => a._memberrate)
                        </div>
                        <div class="form-group">
                            <label>Expense</label>
                            @Html.TextBoxFor(a => a.expnse, new { @class = "form-control ratetext", @id = "_expense" })
                        </div>


                        <div class="form-group">
                            <label>upload Document</label>
                        </div>
                        <div class="form-group input-group input-group-file">

                            <span class="input-group-btn">
                                <span class="btn btn-primary btn-file">
                                    Browse <input type="file" class="form-control" name="file">
                                </span>
                            </span>
                            <input type="text" class="form-control" readonly="">
                        </div>

                        <div class="form-group">
                            <label>Comment</label>
                            @Html.TextAreaFor(a => a.comment, new { @class = "textarea-wysihtml5 form-control", @rows = "6" })
                        </div>
                        <button type="submit" class="btn btn-success btn-sm pull-right"><i class="fa fa-plus"></i> Add </button>
                    }
                </div>
            </div>
        </div>


    </div>

</div>
<script>

    function getrate(memberid) {
      
        if (memberid != 0) {
            var _url = "@Url.Action("get_member_rate","users")"+"?id="+memberid;
            $.get(_url, function (data) {
                $("#_memberrate").val(data);
            });
        } else {
            $("#_memberrate").val("$1");
        }
    }
    getrate('@userid');
   get_Manager_selectbyid('memberid','Technician','T');
    get_jobs('jobid','Job');
    function get_Manager_selectbyid(cntrl,_val,type) {
            var dataString = 'optvalue='+_val+"&memberid=@userid"+"&type="+type;
                    $.ajax
                        ({
                            type: "POST",
                            url: '@Url.Action("get_selcted_member","default")',
                            data: dataString,
                            cache: false,
                            success: function (data) {
                                $("#"+cntrl).html(data).removeAttr('disabled').selectpicker('refresh');
                            }
                        });

    }
    function get_jobs(cntrl,_val) {
            var dataString = 'optvalue='+_val+"&memberid=@userid"+"&jobid=@jobid";
                    $.ajax
                        ({
                            type: "POST",
                            url: '@Url.Action("get_assigned_jobs","default")',
                            data: dataString,
                            cache: false,
                            success: function (data) {
                                $("#"+cntrl).html(data).removeAttr('disabled').selectpicker('refresh');
                                if ("@jobid" != 0) {
                                     getjobdetail("@jobid");
                                }
                            }
                        });

    }
    
    $("#jobid").on("change", function () {
        var _jobid = $("#jobid").val();
        getjobdetail(_jobid);
    });

    function getjobdetail(jobid) {
            var _url = "@Url.Action("getjob","jobs")"+"?id="+jobid;
            $.get(_url, function (data) {
                $("#startdate").val(data.sdate);
                $("#starttime").val(data.stime);
                $("#endtime").val(data.etime);
                $("#_expense").val(data.Expense);
            });
    }
</script>