Models/department.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace hrm.Models
{
    public class department : ErrorModel
    {
        public List<department_items> _dept { get; set; }
        [Required(ErrorMessage = "Please enter name.", AllowEmptyStrings = false)]
        public string dep_name { get; set; }
    }

    public class department_items
    {
        public string name { get; set; }
        public int id { get; set; }
    }
}

Controllers/departmentsController.cs
using hrm.Database;
using hrm.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hrm.Controllers
{
    [AuthorizeVerifiedloggedin]
    public class departmentsController : Controller
    {
        public List<int> _permission;
        public departmentsController()
        {
            int roleid = System.Web.HttpContext.Current.Request.Cookies["_pid"] == null ? 0 : Convert.ToInt16(System.Web.HttpContext.Current.Request.Cookies["_pid"].Value.ToString());
            roleservices _ser = new roleservices();
            _permission = _ser.get_all_active_permissions_bytypeid(6, roleid);
        }
        // GET: departments
        public ActionResult Index()
        {
            if (!_permission.Contains(3))
            {
                return View("unauth");
            }
            var dept = new departmentservices();
            var _model = dept.get_all_active_departments();
            string message = "";
            if (TempData["error"] != null)
            {
                message = TempData["error"].ToString();
            }
            ViewBag.permissions = _permission;
            _model = new helper().GenerateError<department>(_model, message);
            return View(_model);
        }

        public ActionResult update()
        {
            var dept = new departmentservices();
            var _model = dept.get_all_active_departments();
            ViewBag.permissions = _permission;
            _model = new helper().GenerateError<department>(_model, _model.error_text);
            return View("index", _model);
        }

        [HttpPost]
        public ActionResult Index(department _model)
        {
            var dept = new departmentservices();
            int userid = Convert.ToInt16(Request.Cookies["_xid"].Value.ToString());
            ViewBag.permissions = _permission;
            var error_text = dept.add_new_dept(_model.dep_name, userid);
            if (!error_text.ToLower().Contains("error"))
            {
                ModelState.Clear();
            }
            _model = dept.get_all_active_departments();
            _model = new helper().GenerateError<department>(_model, error_text);
            return View(_model);
        }


        [HttpPost]
        public ActionResult update(string department, int deptid)
        {
            var dept = new departmentservices();
            int userid = Convert.ToInt16(Request.Cookies["_xid"].Value.ToString());
            ViewBag.permissions = _permission;
            var error_text = dept.update_dept(department, deptid, userid);
            department _model = new department();
            _model = dept.get_all_active_departments();
            _model = new helper().GenerateError<department>(_model, error_text);
            return View("index", _model);
        }


        public ActionResult delete(int deptid)
        {
            if (!_permission.Contains(20))
            {
                return View("unauth");
            }
            var dept = new departmentservices();
            int userid = Convert.ToInt16(Request.Cookies["_xid"].Value.ToString());
            ViewBag.permissions = _permission;
            var error_text = dept.delete_dept(deptid, userid);
            department _model = new department();
            _model = dept.get_all_active_departments();
            _model = new helper().GenerateError<department>(_model, error_text);
            return View("index", _model);
        }
    }
}

Views/departments/Index.cshtml
@{
    ViewBag.Title = "Department";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int _count = 0;
    var permission = (List<int>)ViewBag.permissions;
}

@model hrm.Models.department

<div class="p-10">
    @*<h2 class="page-title">Department</h2>*@
</div>
<div class="p-30 p-t-none p-b-none">
    @if (!string.IsNullOrEmpty(Model.error_text))
    {
        <div class="alert alert-@Model.alertclass alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
            @Model.error_text
        </div>
    }
    <div id="upload" class="modal fade" data-backdrop="static" data-keyboard="false" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <h4 class="modal-title" id="myModalLabel">Upload Departments</h4>
                </div>
                @using (Html.BeginForm("department", "import", FormMethod.Post, new { @id = "frmsendsms", @enctype = "multipart/form-data" }))
                {

                    <div class="modal-body">
                        <div class="row">
                            <div class="col-sm-12 col-md-12 col-lg-12">
                                <div class="form-group">
                                    <label style="width:100%">Upload a CSV formatted file:</label>
                                    <div class="input-group input-group-file">
                                        <span class="input-group-btn">
                                            <span class="btn btn-primary btn-file">
                                                Browse <input required type="file" id="files" accept=".csv" class="form-control" name="file">
                                            </span>
                                        </span>
                                        <input type="text" class="form-control" readonly="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label style="width:100%">Download Template:</label>
                                    <a href="@Url.Content("~/csvfiles/department.csv")" download="">  <img src="@Url.Content("~/Content/Images/csv.png")" style="width:100px;" /></a>

                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" id="submit-file" class="btn btn-success">Import</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                }
            </div>

        </div>

    </div>
    <div id="mdlupdate" class="modal fade" data-backdrop="static" data-keyboard="false" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <h4 class="modal-title" id="myModalLabel">Edit Department</h4>
                </div>
                @using (Html.BeginForm("update", "departments", FormMethod.Post, new { @id = "frmsendsms" }))
                {<div class="modal-body">
                        <div class="form-group">
                            <label>Department Name :</label>
                            <input type="text" class="form-control" required="" id="deptname" name="department">
                            <input type="hidden" name="deptid" id="deptid" />
                        </div>
                    </div>
                 <div class="modal-footer">
                     <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> Update</button>
                     <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-close"></i> Close</button>

                 </div>
                }
            </div>
        </div>

    </div>
    <div class="row">
        @if (permission.Contains(22))
        {
            <div class="col-lg-4">
                <div class="panel">
                    <div class="panel-body">
                        @using (Html.BeginForm("index", "departments", FormMethod.Post, new { @id = "frmsendsms" }))
                        {
                            <div class="panel-heading">
                                <h3 class="panel-title"> Add Department</h3>
                            </div>
                            <div class="form-group">
                                <label>Department Name</label>
                                <span class="help">e.g. "Account Department"</span>
                                @Html.TextBoxFor(a => a.dep_name, new { @class = "form-control" })
                                @Html.ValidationMessageFor(a => a.dep_name)
                            </div>
                            <button type="submit" class="btn btn-success btn-sm pull-right"><i class="fa fa-plus"></i> Add </button>
                        }
                    </div>
                </div>
            </div>
        }
        <div class="col-lg-8">
            <div class="panel">
                <div class="panel-heading" style="padding-left:20px;">
                    <h3 class="panel-title">
                        All Departments
                        @if (permission.Contains(21))
                        {
                            <a class="btn btn-success btn-sm pull-right" style="margin-right:8px;" onclick="Uploadfile()" href="#">
                                <i class="fa fa-cloud-upload"></i> Upload
                            </a>
                        }
                    </h3>
                </div>
                <div class="panel-body p-none">
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table data-table nowrap table-hover table-ultra-responsive dataTable no-footer">
                                <thead>
                                    <tr>
                                        <th>SL#</th>
                                        <th>Department Name</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model._dept)
                                    {
                                        _count = _count + 1;
                                        <tr role="row" class="odd">
                                            <td>@_count</td>
                                            <td>

                                                @if (permission.Contains(19))
                                                {
                                                    <a href="#" onclick="update('@item.id','@item.name')">@item.name</a>
                                                }
                                                else
                                                {
                                            <a href="#" class="disabledbtn" data-msg="you are not authorized to edit selected department">@item.name</a>
                                                    
                                                }
                                            </td>
                                            <td>
                                                <div class="btn-group pos-static">
                                                    <a class="customedropdown" data-toggle="customedropdown" aria-haspopup="true" aria-expanded="false">
                                                        <i class="fa fa-ellipsis-v fn21"></i>
                                                    </a>
                                                    <div class="dropdown-menu customdropdown-menu" x-placement="bottom-start" style="top: 0px; transform: translate3d(-96px, -18px, 0px);will-change: transform;position: absolute;left: 0px;">

                                                        @if (permission.Contains(19))
                                                        {
                                                            <a class="btn btn-success btn-xs" onclick="update('@item.id','@item.name')"><i class="fa fa-edit"></i> Edit</a>
                                                        }
                                                        else
                                                        {
                                                            <a href="#" class="btn btn-success btn-xs disabledbtn" data-msg="you are not authorized to edit selected department"><i class="fa fa-edit"></i> Edit</a>
                                                        }
                                                        @if (permission.Contains(20))
                                                        {
                                                            <a href="#" class="btn btn-danger btn-xs cdelete" id="@item.id"><i class="fa fa-trash"></i> Delete</a>
                                                        }
                                                        else
                                                        {
                                                            <a href="#" class="btn btn-danger btn-xs disabledbtn" data-msg="you are not authorized to delete selected department"><i class="fa fa-trash"></i> Delete</a>
                                                        }
                                                        </div></div>
                                            </td>
                                        </tr>
                                    }


                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>
<script>
    $(document).ready(function () {
        $('.data-table').DataTable({"bSort" : false, "pageLength": 25});
        /*For Delete Department*/
        $(".cdelete").click(function (e) {
            e.preventDefault();
            var id = this.id;
            bootbox.confirm("Are you sure?", function (result) {
                if (result) {
                    var _url = "@Url.Action("delete","departments")";
                    window.location.href = _url + "?deptid=" + id;
                }
            });
        });
    });
     function update(deptid, deptname) {
            $('#mdlupdate').modal('show');
            $("#deptname").val(deptname);
            $("#deptid").val(deptid);
    }
      function Uploadfile() {
              $('#upload').modal('show');
        }

</script>